[project]
name = "smartnews"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dobadev", email = "doba.fullstack@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "discord-py>=2.7.1",
    "feedparser>=6.0.14",
    "groq>=1.7.0",
    "psycopg[binary]>=3.3.6",
    "pydantic>=2.13.5",
    "python-telegram-bot>=22.8",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
]

[project.scripts]
smartnews = "smartnews:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "ipython>=9.17.1",
    "pytest>=9.1.1",
    "pytest-httpserver>=1.1.5",
    "responses>=0.26.3",
    "ruff>=0.16.8",
    "testcontainers[postgres]>=4.15.0",
]
