sources:
  - name: hacker-news
    url: https://hnrss.org/frontpage
    enabled: true
  # web dev / techstack
  - name: css-tricks
    url: https://css-tricks.com/feed/
    enabled: true
  - name: smashing-magazine
    url: https://www.smashingmagazine.com/feed/
    enabled: true
  # crypto
  - name: decrypt
    url: https://decrypt.co/feed
    enabled: true
  # AI
  - name: ai-news
    url: https://www.artificialintelligence-news.com/feed/
    enabled: true
  # LLM
  - name: simon-willison
    url: https://simonwillison.net/atom/everything/
    enabled: true
